#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libev
Version  : 4.25
Release  : 6
URL      : http://dist.schmorp.de/libev/libev-4.25.tar.gz
Source0  : http://dist.schmorp.de/libev/libev-4.25.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: libev-lib = %{version}-%{release}
Requires: libev-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: 0001-pkg-include-headers.diff

%description
libev is a high-performance event loop/event model with lots of features.
(see benchmark at http://libev.schmorp.de/bench.html)

%package dev
Summary: dev components for the libev package.
Group: Development
Requires: libev-lib = %{version}-%{release}
Provides: libev-devel = %{version}-%{release}
Requires: libev = %{version}-%{release}

%description dev
dev components for the libev package.


%package lib
Summary: lib components for the libev package.
Group: Libraries
Requires: libev-license = %{version}-%{release}

%description lib
lib components for the libev package.


%package license
Summary: license components for the libev package.
Group: Default

%description license
license components for the libev package.


%prep
%setup -q -n libev-4.25
cd %{_builddir}/libev-4.25
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604352969
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604352969
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libev
cp %{_builddir}/libev-4.25/LICENSE %{buildroot}/usr/share/package-licenses/libev/10e633ee2e9f8a961554d0d579f03a1d0755ff3b
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libev/ev++.h
/usr/include/libev/ev.h
/usr/include/libev/event.h
/usr/lib64/libev.so
/usr/share/man/man3/ev.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libev.so.4
/usr/lib64/libev.so.4.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libev/10e633ee2e9f8a961554d0d579f03a1d0755ff3b
